name: Publish layer to starmap

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/starmap-build-multiarch.yml
    with:
      image: ghcr.io/obradovicsl/unikernel-test
      semver: v1.0.9
      archs: "x86_64,"
      nodeType: StoredProcedure
      starmapUrl: https://diligent-smuggler-lanky.ngrok-free.dev
    secrets: inherit
